name: build

on:
  push:
    branches:
      - develop
      - master
      - release/*
  pull_request:
  schedule:
    - cron: '25 6 * * *'

jobs:
  buildnrun:
    name: Integrate and run demo app
    runs-on: macos-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Setup Cordova tools
        run: npm install -g cordova
      - name: Integrate into demo app and run it
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: pushd demoapp && npm i && npm --sUserName=${{ secrets.S_USERNAME }} --sPassword=${{ secrets.S_PASSWORD }} --sPubKey=${{ secrets.S_PUBKEY }} --m2UserName=${{ secrets.M_USERNAME }} --m2Password=${{ secrets.M_PASSWORD }} --m2Url=${{ secrets.M_URL }} run prepareConfig && npm run prepareAndRunOnEmulator
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
