name: build

on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  buildnrun:
    name: Integrate and run demo app
    runs-on: macos-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Setup Cordova tools
        run: npm install -g cordova
      - name: Integrate into demo app and run it
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: pushd demoapp && npm i && npm --sUserName=$S_USERNAME --sPassword=$S_PASSWORD --sPubKey=$S_PUBKEY --m2UserName=$M_USERNAME --m2Password=$M_PASSWORD --m2Url=$M_URL run prepareConfig && npm run prepareAndRunOnEmulator
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          S_USERNAME: ${{ secrets.S_USERNAME }}
          S_PASSWORD: ${{ secrets.S_PASSWORD }}
          S_PUBKEY: ${{ secrets.S_PUBKEY }}
          M_USERNAME: ${{ secrets.M_USERNAME }}
          M_PASSWORD: ${{ secrets.M_PASSWORD }}
          M_URL: ${{ secrets.M_URL }}
