name: Release a new version from master

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the library'
        required: true
      confirmBranch:
        description: 'Confirm release branch'
        required: true
      command:
        description: 'Library deploy command'
        required: false
        default: prepare push deploy -v2 --any-branch 

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Set Github Token
        run: git config --global url."https://${{ secrets.GH_CI_TOKEN }}@github".insteadOf https://github
      - name: Make sure we're on master branch
        run: |
          [[ $GITHUB_REF == refs/heads/${{ github.event.inputs.confirmBranch }} ]] || exit 1
      - name: Publish the library
        uses: wultra/library-deploy@develop
        with:
          script-parameters: ${{ github.event.inputs.version }} ${{ github.event.inputs.command }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}